# Generated by Django 5.1.1 on 2024-10-22 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offices', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=100)),
                ('member_of', models.CharField(max_length=255)),
                ('tour_types', models.CharField(max_length=255)),
                ('price_ranges', models.CharField(max_length=100)),
                ('destinations', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=15)),
                ('websites', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
